### ISSUE TITLE
How does the app know that there's an admin logged in in addition to impersonated user? 

### ISSUE THREAD

**Issue by adanielyan** [alan2207/epic-stack-with-user-impersonation#1]
This is a great feature, thank you for this example. 

I have a question though. How does the app know that there is an admin user logged in addition to the user who is being impersonated? I mean the regular user wouldn't have the "Stop impersonating" menu item in the profile menu, right? Will it still be there after refreshing the page? If so, how do you let the app know that there's an admin user logged in too?

**Comment by alan2207** [comment]
Hey @adanielyan, you can follow this flow:

https://github.com/alan2207/epic-stack-with-user-impersonation/blob/b4fbe5c1638cf8ae5ffd5b73998348f8c736ec02/app/root.tsx#L246

https://github.com/alan2207/epic-stack-with-user-impersonation/blob/b4fbe5c1638cf8ae5ffd5b73998348f8c736ec02/app/root.tsx#L119

https://github.com/alan2207/epic-stack-with-user-impersonation/blob/b4fbe5c1638cf8ae5ffd5b73998348f8c736ec02/app/utils/auth.server.ts#L178

There is no magic, we are just checking if we have `impersonatorSessionId` available and use that to get the impersonator.

**Comment by adanielyan** [comment]
Thank you! I suspected something like this but wasn't sure where to look for it. Another question, I tried to find it in the code but couldn't. How do you know that the impersonator is admin or has a permission to impersonate another user? Theoretically any user can add the impersonatorSessionId cookie with their current token to the request.

**Comment by alan2207** [comment]
Hey @adanielyan , great question!

The impersonate action is protected, it will not allow to impersonate if you are not an admin:
https://github.com/alan2207/epic-stack-with-user-impersonation/blob/b4fbe5c1638cf8ae5ffd5b73998348f8c736ec02/app/routes/_auth%2B/impersonate.tsx#L25

The admin users page is also allowed to be visited only by admins.
https://github.com/alan2207/epic-stack-with-user-impersonation/blob/b4fbe5c1638cf8ae5ffd5b73998348f8c736ec02/app/routes/admin%2B/users.tsx#L10

And no one can know what's in the session or modify it if they don't have access to the session storage's secret:
https://github.com/alan2207/epic-stack-with-user-impersonation/blob/b4fbe5c1638cf8ae5ffd5b73998348f8c736ec02/app/utils/session.server.ts#L9C1-L9C1

I would say it's pretty secure but feel free to create an issue/PR if you still find any vulnerabilities.

**Comment by adanielyan** [comment]
Thank you for explaining. Since you need to have another user's session token in order to impersonate them, there is no practical way to do it without being logged in as admin in the first place. Thanks!
